[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "list"
version = "0.1.0"
description = "An improved version of the List type"
readme = "README.md"
authors = [
  {name = "Daniel Roy Greenfeld", email = "daniel@feldroy.com"}
]
maintainers = [
  {name = "Daniel Roy Greenfeld", email = "daniel@feldroy.com"}
]
classifiers = [

]
license = {text = "MIT"}

[project.urls]

homepage = "https://example.com"

repository = "https://github.com/pydanny/listplus.git"
changelog = "https://github.com/pydanny/listplus/blob/master/CHANGELOG.md"
bugs = "https://github.com/pydanny/listplus/issues"

